### PR TITLE
#163582815 Remove SECRET_KEY from source control

### PR DESCRIPTION
**Pull request by karuhanga**
#### What does this PR do?
- Remove `SECRET_KEY` from source control to avoid vulnerabilities that come with exposing this key
- Allow auto loading environment variables from an optional `.env` file
#### Description of Task to be completed?
- remove the `SECRET_KEY` from source control and use and environment variable to access it
- update heroku `app.json` to copy the `SECRET_KEY` value from `staging`
- for flexibility, allow one to define environment variables in a `.env` file, to minimize the need for manually exporting variables
#### How should this be manually tested?
- set the `SECRET_KEY` environment variable
- run the project
#### Any background context you want to provide?
**BREAKING CHANGE**
- the `SECRET_KEY` environment variable will now have to be set in an environment before running the project
#### What are the relevant pivotal tracker stories?
- [#163582815](https://www.pivotaltracker.com/story/show/163582815)

### CODE REVIEW

**Review by codjoero — CHANGES_REQUESTED** [review]
Hey @Karuhanga , good job there, we are more secure now. I was wondering though, instead of using environment variables could we make it a bit easier by adding our secrets, allowed_hosts and the likes in a .env file. we could also make use of python decouple to manage our link to the .env otherwise they're going to be a lot of env variables to export.

**Comment by karuhanga** [comment]
> Hey @Karuhanga , good job there, we are more secure now. I was wondering though, instead of using environment variables could we make it a bit easier by adding our secrets, allowed_hosts and the likes in a .env file. we could also make use of python decouple to manage our link to the .env otherwise they're going to be a lot of env variables to export.

Absolutely. Just implemented this functionality. Kindly review the changes.

**Review by fahdjamy — APPROVED** [review]

**Review by oma0256 — APPROVED** [review]

**Review by codjoero — APPROVED** [review]
LGTM

**Review by missvicki — APPROVED** [review]

**Review by fahdjamy — APPROVED** [review]

**Comment by malep2007** [comment]
@Karuhanga , this build is failing. Can you get the updated version on develop and cross-check to find out what is wrong?

**Pull request merged**
