### PR TITLE
#163383196 Add functionality to report an article

### PR DESCRIPTION
**Pull request by oma0256**
**What does this PR do?**
 - Allow a user to report an article if they find it offensive.
 - Allow admin to retrieve all the reports made.
 - Allow users to retrieve the reports they made.

**How should this be manually tested?**
 - Download and install postman onto you're local machine
 - Open postman
 - Then visit the route `https://ah-backend-summer-stagin-pr-46.herokuapp.com/api/v1/users/` and provide username, email and password to register. Then visit the route `https://ah-backend-summer-stagin-pr-46.herokuapp.com/api/v1/users/login/` and provide email and password to login. `
 - Then visit the route `https://ah-backend-summer-stagin-pr-46.herokuapp.com/api/v1/articles/<slug>/report` to report an article.

**Screenshots**
screen shot 2019-02-20 at 12 54 32

**What are the relevant pivotal tracker stories?**
[#163383196](https://www.pivotaltracker.com/n/projects/2240000/stories/163383196)

### CODE REVIEW

**Review by karuhanga — APPROVED** [review]
LGTM

**Review by fahdjamy — APPROVED** [review]
LGTM

**Review by missvicki — APPROVED** [review]
LGTM. Nice work

**Comment by malep2007** [comment]
@oma0256 some merge conflicts

**Review by malep2007 — APPROVED** [review]
Just ensure that the merge conflicts are resolved.

**Comment by malep2007** [comment]
@oma0256 we shall consider breaking the views to separate units to guarantee a better of enforcing "separation of concerns"

**Pull request merged**
