### PR TITLE
#163383167 Setup application database configurations

### PR DESCRIPTION
**Pull request by karuhanga**
#### What does this PR do?
- setup application to use PostgreSQL as backend engine
- update settings to use settings module with appropriate environment configurations
- make pending migrations
#### Description of Task to be completed?
- have the application running with a postreSQL backend, in place of the current SQLite3 engine
#### How should this be manually tested?
- clone the repo
- install the requirements `pip install -r requirements.txt`
- set the `ENVIRONMENT` environment variable to one of `production`, `staging` or `development`
- set the `DATABASE_URL`, `STAGING_DATABASE_URL` or `DEVELOPMENT_DATABASE_URL` environment variable respectively, based on the `ENVIRONMENT` environment variable. This URL must follow the postgres connection variable convention(https://www.postgresql.org/docs/current/libpq-connect.html#LIBPQ-CONNSTRING)
- run the server `python manage.py runserver`
#### Any background context you want to provide?
- the previous settings configuration in `settings.py` was not sufficient for the project, hence the change to a module system
#### What are the relevant pivotal tracker stories?
- #163383167

### CODE REVIEW

**Review by missvicki — COMMENTED** [review]
Amazing work Lincoln. I like the different stages in environment that you've set up. I think it would be necessary to add a staging environment as well for when a PR is made and that way when the PR is merged the app would be changed to the staging environment

**Comment by codjoero** [comment]
Good work @Karuhanga, the different stages are helpful, and the added staging environment makes much more sense.

**Comment by fahdjamy** [comment]
Great work @Karuhanga.

**Review by codjoero — APPROVED** [review]
LGTM

**Comment by missvicki** [comment]
@Karuhanga great work. LGTM

**Comment by pbkabali** [comment]
@Karuhanga this is great!

**Pull request merged**
