### PR TITLE
#163383158 Write tests for the available functionalities

### PR DESCRIPTION
**Pull request by oma0256**
**What does this PR do ?**
Tests authentication functionality

**Description of Task to be completed?**
 - Tests user registration functionality
 - Test user login functionality

**How should this be manually tested?**
 - Clone the repo onto your local machine
 - Create and activate virtual environment
 - Move into the project directory
`pip3 install -r requirements.txt`
`python3 manage.py test`

**What are the relevant pivotal tracker stories?**
[#163383158](https://www.pivotaltracker.com/story/show/163383158)

### CODE REVIEW

**Comment by fahdjamy** [comment]
This is great work @oma0256. Great job on the comments in the code and for splitting up the test base from the tests.

**Comment by karuhanga** [comment]
Good work guys especially on keeping the whole thing DRY and keeping the test data in a single file.
A few thoughts;
- I think the test data should be in properly labelled classes, to properly separate classes for each group of tests
- I think the `register_user` method([here](https://github.com/andela/ah-backend-summer/blob/3b77617b183f6d8ac3d5f669e5e1f97afda2ab47/authors/apps/authentication/tests/base_class.py#L17)) in `BaseTest` could be more descriptive, like `register_test_user`
- The `register_user` method is called in all the tests in the `LoginTest` class. You could simplify this by overriding the `setUp` method in the `LoginTest` class to include the call to `register_user`

**Comment by pbkabali** [comment]
Nice work @oma0256 and @missvicki. putting the test data and tests in different files makes your work easy to follow and understand. Still trying to figure out thou why there is two sets of test-user registration data.

**Comment by oma0256** [comment]
@pbkabali Thank you for that notice and @Karuhanga great feedback me and @missvicki will start on this

**Comment by missvicki** [comment]
> Good work guys especially on keeping the whole thing DRY and keeping the test data in a single file.
> A few thoughts;
> 
> * I think the test data should be in properly labelled classes, to properly separate classes for each group of tests
> * I think the `register_user` method([here](https://github.com/andela/ah-backend-summer/blob/3b77617b183f6d8ac3d5f669e5e1f97afda2ab47/authors/apps/authentication/tests/base_class.py#L17)) in `BaseTest` could be more descriptive, like `register_test_user`
> * The `register_user` method is called in all the tests in the `LoginTest` class. You could simplify this by overriding the `setUp` method in the `LoginTest` class to include the call to `register_user`

Great suggestions. We are not able to do the classes in one file as that will make the file lines longer than the defined conventions. But, we shall instead create separate files for login and register user data. Hope that will be easier to read

**Pull request merged**
